### ISSUE TITLE
clone all script throws error

### ISSUE THREAD

**Issue by ashriram** [danwallach/github-classroom-utils#2]
***How to replicate****

git clone https://github.com/danwallach/github-classroom-utils/

Update github_token and organization name

 python3.7 github_clone_all.py --prefix Ass3 --out Ass3

Github setup:
https://github.com/org/Ass3-Student1
https://github.com/org/Ass3-Student2 .....

***error***

Cached result for org is missing or outdated
Traceback (most recent call last):
  File "github_clone_all.py", line 42, in <module>
    filtered_repo_list = query_matching_repos(github_organization, github_prefix, github_token)
  File "/private/tmp/github-classroom-utils/github_scanner.py", line 212, in query_matching_repos
    result = query_repos_cached(github_organization, github_token, verbose)
  File "/private/tmp/github-classroom-utils/github_scanner.py", line 161, in query_repos_cached
    github_token, verbose)
  File "/private/tmp/github-classroom-utils/github_scanner.py", line 313, in parallel_get_github_endpoint_paged_list
    link_header = page1_result.headers["Link"]
  File "/usr/local/lib/python3.7/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'link'

**Fix** 
The pagination logic in github_scanner appears broken. If the org has only one page then the "link" key in the header is empty. I would push a fix but not sure which other scripts might deal with pagination.
Line 319-328
    num_pages = 1 # Default page value
    if ("Link" in page1_result.headers):
        link_header = page1_result.headers["Link"]
        p = re.compile('page=(\\d+)>; rel="last"')
        m = p.findall(link_header)
        if len(m) != 1:
            if verbose:
                print("Malformed header, didn't have pagination!")
            return page1_result.json()
        num_pages = int(m[0])

**Comment by danwallach** [comment]
Ahh, okay. I'll work this in and get a patch out ASAP. Please email me privately (dwallach@gmail.com) and I'll contact you when ready so you can test. I've got something like 60+ pages with my students, so I can't test this myself.

**Comment by danwallach** [comment]
Fixed. Check it out and let me know if it works for you.
